version: 2.1

global-variables: &global-variables
  SERVICE_NAME: eth
  BINARY_DIR: /mnt/chaindata/geth/bin

jobs:
  build-and-upload:
    working_directory: /build
    docker:
      - image: xozzslip/ubuntu-go
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: '.'
      - run:
          name: Go Build & Publish
          environment:
            <<: *global-variables
          command: |
            VERSION=$(git log --decorate --pretty=oneline @ | egrep 'v[0-9\.]+[A-Za-z0-9\.-]*' -o | cut -d ":" -f2 | head -1 | sed -e 's/^ *//')
            make geth
            ls -lah ./build/bin
            echo uploading to $BINARY_DIR/geth-$VERSION-$CIRCLE_SHA1
            echo $SSH_PRIVATE_KEY > /tmp/id_rsa
            chmod 400 /tmp/id_rsa
            scp -i /tmp/id_rsa -o StrictHostKeyChecking=no ./build/bin/geth $SSH_USERNAME@$SSH_IP:$BINARY_DIR/geth-$VERSION-$CIRCLE_SHA1
            cd ..
      - persist_to_workspace:
          root: '.'
          paths:
            - '.'

  deploy:
    docker:
      - image: xozzslip/ubuntu-go
    steps:
      - setup_remote_docker
      - run:
          name: Deploy
          environment:
            <<: *global-variables
          command: |
            BINARY_NAME=$(ssh -o StrictHostKeyChecking=no -t $SSH_USERNAME@$SSH_IP "ls `echo $BINARY_DIR` | grep `echo $CIRCLE_SHA1` | tr -d '\n'")
            BINARY_PATH=$BINARY_DIR$BINARY_NAME
            echo "going to deploy $BINARY_PATH"
            SERVICE_PATH=/etc/systemd/system/$SERVICE_NAME.service
            ssh -o StrictHostKeyChecking=no -t $SSH_USERNAME@$SSH_IP "sed -Ei 's@ExecStart=[^[:space:]]+@ExecStart=`echo $BINARY_PATH`@g' `echo $SERVICE_PATH`"
            echo "updated service file"
            ssh -o StrictHostKeyChecking=no -t $SSH_USERNAME@$SSH_IP "systemctl daemon-reload && systemctl stop `echo $SERVICE_NAME` && systemctl start `echo $SERVICE_NAME`"

workflows:
  build:
    jobs:
      - build-and-upload:
          context: ankrscan-nodes
          filters:
            branches:
              only: feature/full-block-api
      - approve:
          filters:
            branches:
              only: feature/full-block-api
          type: approval
      - deploy:
          context: ankrscan-nodes
          requires:
            - approve
            - build-and-upload
          filters:
            branches:
              only: feature/full-block-api